// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5rrATvqoYSyhikTLlbkXt5_1kNzIHPc',
    appId: '1:815923466555:web:32a1819b65f63905f2a71e',
    messagingSenderId: '815923466555',
    projectId: 'moviedetailsapp-9f000',
    authDomain: 'moviedetailsapp-9f000.firebaseapp.com',
    storageBucket: 'moviedetailsapp-9f000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gSUAgTO6OvjZotYWFDiZ-mFnVL3Cryk',
    appId: '1:815923466555:android:d15226b689977041f2a71e',
    messagingSenderId: '815923466555',
    projectId: 'moviedetailsapp-9f000',
    storageBucket: 'moviedetailsapp-9f000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAas-5_P3SuMCtipQed3uxao1i809ZJ41c',
    appId: '1:815923466555:ios:16f328db446c3faff2a71e',
    messagingSenderId: '815923466555',
    projectId: 'moviedetailsapp-9f000',
    storageBucket: 'moviedetailsapp-9f000.appspot.com',
    iosClientId: '815923466555-qtcss1cfbb4stcainh7f7vl4k8d2c7mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAas-5_P3SuMCtipQed3uxao1i809ZJ41c',
    appId: '1:815923466555:ios:16f328db446c3faff2a71e',
    messagingSenderId: '815923466555',
    projectId: 'moviedetailsapp-9f000',
    storageBucket: 'moviedetailsapp-9f000.appspot.com',
    iosClientId: '815923466555-qtcss1cfbb4stcainh7f7vl4k8d2c7mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
